locales:
  en:
    question-file: "csv/questions_en_EN.csv"
    select: "Please select language:"
    select-lang-En: "1. English(EN)"
    select-lang-Ru:  "2. Russian(RU)"
    registration-greeting: "Welcome to the quick test program!!!"
    registration-promptedEnterFirstName: "Enter your first name:"
    registration-promptedEnterSecondName: "Enter your second name:"
    registration-promptedEnterAge: "Enter your age:"
    registration-notNumberError: "You didn't enter an integer!!! Enter the age as an integer."
    answer-correct: "Correct answer!"
    answer-wrong: "Wrong answer!"
    answer-result: "Your result %d correct answers."
    not-registration: "You are not registered! Sign up!"
    not-start: "Start question session"
    test-completed: "Test completed! See the results!"
    test-not-completed: "Test not completed! Answer the following question!"
    test-result: "To pass the test you need to give %d correct answer."
    test-passed: "Test passed!"
    test-failed: "Test failed!"

  ru:
    question-file: "csv/questions_ru_RU.csv"
    select: "Пожалуйста, выберите язык:"
    select-lang-En: "1. Английский(EN)"
    select-lang-Ru: "2. Русский(RU)"
    registration-greeting: "Вас приветствует программа быстрого тестирования!!!"
    registration-promptedEnterFirstName: "Введите имя:"
    registration-promptedEnterSecondName: "Введите фамилию:"
    registration-promptedEnterAge: "Введите ваш возраст:"
    registration-notNumberError: "Вы ввели не число!!! Введите ваш возраст целым числом."
    answer-correct: "Правильный ответ!"
    answer-wrong: "Неправильный ответ!"
    answer-result: "Ваш результат %d верный(ых) ответ(а)."
    not-registration: "Вы не зарегистрированы! Зарегистрируйтесь!"
    not-start: "Запустите тесты!"
    test-completed: "Тест завершен! Посмотрите результаты!"
    test-not-completed: "Тест не завершен! Ответьте на следующий вопрос! "
    test-result: "Для прохождения теста вам необходимо дать %d верный(ых) ответ(а)."
    test-passed: "Тест пройден!"
    test-failed: "Тест провален!"
min:
  point: 3
